services:
    app:
        build: .
        container_name: dev
        ports:
            - "3000:3000"
        environment:
            - NODE_OPTIONS=--experimental-modules
        volumes:
            - ./src:/home/app/src
