const authRoutes = require("./auth");
const userRoutes = require("./user");
const companyRoutes = require("./company");
const adminRoutes = require("./admin");
const dashboardRoutes = require("./dashboard");
const jobRoutes = require("./job");
const apiRoutes = require('./api');
const chatRoutes = require('./chat');
module.exports = { authRoutes, userRoutes, companyRoutes, adminRoutes, dashboardRoutes, jobRoutes, apiRoutes, chatRoutes };
